CREATE PROCEDURE [dbo].[SPR_CASO_ENCURSO2]
(
	@USUA_ID		BIGINT,
	@EMPRESA_ID		INT,
	@CASO_TIPO_CD	VARCHAR(10)
)
/* =============================================
-- ============================================= */
AS
BEGIN

	SET NOCOUNT ON;

	SELECT
		CASO.CASO_ID,
		SUCURSAL,
		CASO_NU,
		CASO.ESTADO_CD,

		CASE 
			WHEN CASO.CASO_TIPO_CD = 'PROGRAMADO' AND CASO.ESTADO_CD = 'ARRIBADO' THEN 'Comenzado' 
			WHEN CASO.CASO_TIPO_CD = 'PROGRAMADO' AND CASO.ESTADO_CD = 'ACEPTADO' AND CASO_SUPERVISOR.CASO_ID IS NULL THEN 'Aceptado'
			WHEN CASO.CASO_TIPO_CD = 'PROGRAMADO' AND CASO.ESTADO_CD = 'ACEPTADO' AND CASO_SUPERVISOR.CASO_ID IS NOT NULL AND CASO.TECNICO_ID IS NULL THEN 'Planificado'
			WHEN CASO.CASO_TIPO_CD = 'PROGRAMADO' AND CASO.ESTADO_CD = 'ACEPTADO' AND CASO_SUPERVISOR.CASO_ID IS NOT NULL AND CASO.TECNICO_ID IS NOT NULL THEN 'Asignado'

			ELSE ESTADO.NOMBRE 
		END AS ESTADO,

		--PRESTADOR.NOMBRE AS PRESTADOR,
		[TECNICO].NOMBRE AS TECNICO,
		[SUPERVISOR].NOMBRE AS SUPERVISOR,
		SOLICITANTE,
		PEDIDO,
		--PROPUESTO,
		--ACEPTADO,
		--ARRIBADO,
		--FINALIZADO,
		
		CONVERT(BIT, 0) AS HAY_CHAT_SIN_LEER,
		--dbo.[hayChatPendienteOperador](CASO.CASO_ID, @USUA_ID) AS HAY_CHAT_SIN_LEER,

		--ESTADO.ORDEN AS ESTADO_ORDEN,

		TIPO_URGENCIA.NOMBRE AS URGENCIA,

		ESTADO_MATERIALES.NOMBRE AS ESTADO_MATERIALES,
		ESTADO_PROVEEDOR.NOMBRE AS ESTADO_PROVEEDOR,

		--[ALERTA].ALERTA_ORDEN,
		[ALERTA].ALERTA_CD,
		[ALERTA].ALERTA_DS,

		ACTIVO.NOMBRE AS ACTIVO,

		CASO.CREATED_DT		 AS CASO_CREACION,
		CASO.PROBLEMA_NOMBRE AS CASO_PROBLEMA_NOMBRE,
		CASO.OBSERVACION AS CASO_OBSERVACION,

		ESTIMADO_DESDE_DT,
		ESTIMADO_HASTA_DT

	FROM CASO
		
		INNER JOIN ESTADO
		ON ESTADO.ESTADO_CD = CASO.ESTADO_CD

		LEFT JOIN CASO_SUPERVISOR
		ON CASO_SUPERVISOR.CASO_ID = CASO.CASO_ID

		LEFT JOIN ESTADO_MATERIALES
		ON ESTADO_MATERIALES.ESTADO_CD = CASO_SUPERVISOR.MATERIALES_ESTADO_CD

		LEFT JOIN ESTADO_PROVEEDOR
		ON ESTADO_PROVEEDOR.ESTADO_CD = CASO_SUPERVISOR.PROVEEDOR_ESTADO_CD

		LEFT JOIN TIPO_URGENCIA
		ON TIPO_URGENCIA.TIPO_URGENCIA_ID = CASO.TIPO_URGENCIA_ID

		--LEFT JOIN PRESTADOR
		--ON PRESTADOR.PRESTADOR_ID = CASO.PRESTADOR_ID

		LEFT JOIN USUARIO AS [TECNICO]
		ON [TECNICO].USUARIO_ID = CASO.TECNICO_ID

		LEFT JOIN USUARIO AS [SUPERVISOR]
		ON [SUPERVISOR].USUARIO_ID = CASO.SUPERVISOR_ID

		LEFT JOIN ACTIVO
		ON ACTIVO.ACTIVO_ID = CASO.ACTIVO_ID

		CROSS APPLY dbo.GetAlerta(CASO.CASO_ID) AS [ALERTA]

	WHERE CASO.DELETED_ID IS NULL
	AND CASO.EMPRESA_ID = @EMPRESA_ID
	AND CASO.CASO_TIPO_CD = @CASO_TIPO_CD
	--AND PROPUESTO IS NOT NULL -- No pendiente
	AND FINALIZADO IS NULL -- No Finalizado (ni Cancelado, ni Aprobado) 



	RETURN;
END
GO
